name: Bump CLI version
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: cli-updates
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Bump CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          scripts/replace-cli-version.sh
      - name: Create the PR
        uses: koesie10/create-app-pr-action@v1
        id: create-pr
        with:
          commit-message: Bump CLI version from ${{ env.PREVIOUS_VERSION }} to ${{ env.LATEST_VERSION }} for integration tests
          title: Bump CLI Version to ${{ env.LATEST_VERSION }} for integration tests
          body: >
            Bumps CLI version from ${{ env.PREVIOUS_VERSION }} to ${{ env.LATEST_VERSION }}
          head-branch: "github-actions/bump-cli"
          base-branch: "main"
          github-app-id: ${{ secrets.APP_GITHUB_APP_ID }}
          github-installation-id: ${{ secrets.APP_GITHUB_INSTALLATION_ID }}
          github-private-key: ${{ secrets.APP_GITHUB_PRIVATE_KEY }}
