name: Bump CLI version
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - .github/actions/create-pr/action.yml
  schedule:
  - cron: 0 0 */14 * * # run every 14 days

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Bump CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          scripts/replace-cli-version.sh
      - name: Commit, Push and Open a PR
        uses: ./.github/actions/create-pr
        with:
          token: ${{ github.token }}
          base-branch: refs/heads/main
          head-branch: bump-cli
          commit-message: Bump CLI version from ${{ env.PREVIOUS_VERSION }} to ${{ env.LATEST_VERSION }} for integration tests
          title: Bump CLI Version to ${{ env.LATEST_VERSION }} for integration tests
          body: >
            Bumps CLI version from ${{ env.PREVIOUS_VERSION }} to ${{ env.LATEST_VERSION }}
