name: Bump CLI version
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/actions/create-pr/action.yml
  schedule:
  - cron: 0 0 */14 * * # run every 14 days

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Bump CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          scripts/replace-cli-version.sh
      - name: Configure actors
        shell: bash
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit, Push and Open a PR
        uses: ./.github/actions/create-pr
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base-branch: refs/heads/main
          head-branch: bump-cli
          commit-message: Bump CLI version from $PREVIOUS_VERSION to $LATEST_VERSION for integration tests
          title: Bump CLI Version to $LATEST_VERSION for integration tests
          body: >
            Bumps rom $PREVIOUS_VERSION to $LATEST_VERSION